### ISSUE TITLE
[FEAT]: Add ability to add nfs to `persistence`

### ISSUE THREAD

**Issue by Brice187** [pmoscode-helm/jdownloader2#40]
### Description

I have a dedicated NAS Box in my homelab network. Jdownloader2 is running on a baremetal (NUCs) Kubernetes Cluster.

Ability to download to NAS directly would be really nice. e.g.:

```
persistence:
  config:
    enabled: true
    mountPath: "/config"
    size: 2Gi
  output:
    enabled: true
    type: nfs
    path: /share/Multimedia/downloads
    server: 192.168.7.26
    mountPath: "/output"
```

### Additional Information

I know there is a workaround manually creating a PV/PVC with storageClass "nfs", but this is imho an overkill for a homelab setup.
